### ISSUE TITLE
Module not found WSL

### ISSUE THREAD

**Issue by Pilchh** [ecosse3/nvim#48]
I have just tried installing the config in WSL 2 running Arch I get the following error:
```
Error detected while processing /home/pilchh/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/pilchh/.config/nvim/init.lua:1: module 'impatient' not found:
        no field package.preload['impatient']
        no file './impatient.lua'
        no file '/usr/share/luajit-2.1.0-beta3/impatient.lua'
        no file '/usr/local/share/lua/5.1/impatient.lua'
        no file '/usr/local/share/lua/5.1/impatient/init.lua'
        no file '/usr/share/lua/5.1/impatient.lua'
        no file '/usr/share/lua/5.1/impatient/init.lua'
        no file './impatient.so'
        no file '/usr/local/lib/lua/5.1/impatient.so'
        no file '/usr/lib/lua/5.1/impatient.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/pilchh/.config/nvim/init.lua:1: in main chunk
Press ENTER or type command to continue
```

I'm not sure if this is an issue with WSL 2 or something else entirely.

**Comment by ecosse3** [comment]
Not sure why it happened. Looks like you didn't run `:PackerInstall` or `:PackerSync` after the first run or sth like that. I fixed that error in case that happens. Please check on `dev` branch.

**Comment by Pilchh** [comment]
> Did you install Ecovim by installation script? `bash <(curl -s https://raw.githubusercontent.com/ecosse3/nvim/master/.install/run.sh)`

Yes, I used the install script. I'll try the script in the dev branch and let you know how it goes.

**Comment by ecosse3** [comment]
@Pilchh Looks like packer was not installed successfully somehow. Please refer to installation guide from the official repo: https://github.com/wbthomason/packer.nvim

I've tested installing Ecovim from scratch again and it works fine.

**Comment by Pilchh** [comment]
Alright, no worries. Must be an issue with WSL.

**Comment by Pilchh** [comment]
After manually reinstalling packer, I still can't seem to get it to work... Not quite sure why I'll have more of a look into it and report back.
